name: Compile asar

on:
  push:
    branches:
      - compile
  pull_request:
    branches:
      - compile
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: pnpm/action-setup@v2.2.4
      with:
        version: 7.13.4
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
    - run: pnpm recursive install
    - run: pnpm run dist
    - uses: actions/upload-artifact@v3
      with:
        name: betterdiscord.asar
        path: dist/betterdiscord.asar
